name = "pathwayai"
main = "functions/api/_worker.js"
compatibility_date = "2026-03-10"

[build]
command = "bash build.sh"

[assets]
directory = "./public"

[[kv_namespaces]]
binding = "JOB_CACHE"
id = "0af3f441620247328294697c887f85dc"
preview_id = "0af3f441620247328294697c887f85dc"

[[kv_namespaces]]
binding = "YOUTUBE_CACHE"
id = "7fa79d5f69bf48fabb2282cd90f0fd0c"
remote = true

[[d1_databases]]
binding = "DB"
database_name = "pathwayai-db"
database_id = "90a57a9c-fcfd-47ed-af55-0f5a399f673b"
